# Generated by Django 2.2.4 on 2020-03-24 08:26

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(blank=True, max_length=15, verbose_name='Telefon')),
                ('gender', models.CharField(blank=True, choices=[('K', 'Kişi'), ('Q', 'Qadın'), ('gender', 'gender')], default='gender', max_length=12, verbose_name='Cinsi')),
                ('bio', models.CharField(blank=True, max_length=100, verbose_name='Haqqında')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum tarixi')),
                ('profile_photo', models.ImageField(blank=True, default='default/unnamed.jpg', null=True, upload_to=accounts.models.upload_to, verbose_name='Profil şəkli')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users Profiles',
            },
        ),
    ]
